---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: book-catalog-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: book-catalog
  template:
    metadata:
      labels:
        app: book-catalog
    spec:
      containers:
      - name: book-catalog
        image: sit722mk.azurecr.io/book_catalog_service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://sit722mkdb_exq5_user:EbwsVUopkOJILWCAhg6daT8weKYSp7Us@dpg-crifujm8ii6s73f33sug-a.oregon-postgres.render.com/sit722mkdb_exq5"
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: inventory-management-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: inventory-management
  template:
    metadata:
      labels:
        app: inventory-management
    spec:
      containers:
      - name: inventory-management
        image: sit722mk.azurecr.io/inventory_management_service:latest
        imagePullPolicy: IfNotPresent
        ports:
        - containerPort: 8000
        env:
        - name: DATABASE_URL
          value: "postgresql://sit722mkdb_exq5_user:EbwsVUopkOJILWCAhg6daT8weKYSp7Us@dpg-crifujm8ii6s73f33sug-a.oregon-postgres.render.com/sit722mkdb_exq5"

---
apiVersion: v1
kind: Service
metadata:
  name: book-catalog-service
spec:
  type: LoadBalancer
  selector:
    app: book-catalog
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      

---
apiVersion: v1
kind: Service
metadata:
  name: inventory-management-service
spec:
  type: LoadBalancer
  selector:
    app: inventory-management
  ports:
    - protocol: TCP
      port: 8000
      targetPort: 8000
      